### ISSUE TITLE
Kaggle Submission Issue: Image Dimensions Mismatch

### ISSUE THREAD

**Issue by lucashu1** [kamalkraj/DATA-SCIENCE-BOWL-2018#1]
Hi, thanks for putting this up! I ran the script and everything seems to work, but when I go to submit the outputted .csv on Kaggle, I'm getting this error message:

```
4 Exceptions:

One or more submitted values exceeded the image dimensions.

One or more submitted values exceeded the image dimensions.

One or more submitted values exceeded the image dimensions.

One or more submitted values exceeded the image dimensions.
```

Have you gotten any errors like this? I'm assuming it has something to do with the upsampling/RLE conversion. If you're not getting this, then maybe I should just try re-downloading the data and seeing if that fixes it.

Thanks in advance!

**Comment by morenoh149** [comment]
@lucashu1 I'm not seeing your issue, I was able to fork, clone this repo, import into colab, train the NN and produce a submission csv that Kaggle accepted. Could you share a link to your colab notebook?

**Comment by lucashu1** [comment]
@morenoh149 I actually ran the script again a little bit later (perhaps after re-downloading the data, I honestly forget) and the issue disappeared! I'll mark this as resolved.
